config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :locations
  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	geocoded_by :address
	after_validation :geocode
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address
	after_validation :geocode
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @Restaurant = Location.all
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:order, :address, :latitude, :longitude)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
      @locations = Location.all
      @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
          marker.lat location.latitude
          marker.lng location.longitude
          marker.title location.title
      end
  end


  # GET /locations/1
  # GET /locations/1.json
  def show
    @my_array = Array.new
    if @location.nearbys.present?
      for location in @location.nearbys(20)
        @my_array.push(location)
      end
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :title, :latitude, :longitude, :area, :inside_zone, :outsite_zone)
      #puts :shape
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/customers/_form.html.erb
<div class="text-center">
  <%= form_with(model: customer, local: true) do |form| %>
    <% if customer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
        <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :order %>
      <%= form.text_field :order, id: :customer_order, :required=> true %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address, id: :customer_address, :required=> true %>
    </div>
    <div class="actions">
      <%= form.submit "Place Order", :class=> "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="text-center">
    <h1>New Orders</h1>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Address</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.order %></td>
              <td><%= customer.address %></td>
              <td><%= customer.latitude %></td>
              <td><%= customer.longitude %></td>
              <td><%= link_to 'Show', customer %></td>
              <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
              <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>

    <%= link_to 'New Order', new_customer_path %>
  </div>
</div>

app/views/customers/new.html.erb
<div class="text-center">
	<h1>Place Your Order here</h1>

	<%= render 'form', customer: @customer %>

	<%= link_to 'Back', customers_path %>
</div>

app/views/customers/show.html.erb
<div class="container text-center">
	<h2>Customer Address Details</h2>
	<p id="notice"><%= notice %></p>
	<p>
		<strong>Order:</strong>
		<%= @customer.order %>
	</p>
	<p>
		<strong>Address:</strong>
		<%= @customer.address %>
	</p>
	<p>
		<strong>Latitude:</strong>
		<%= @customer.latitude %>
	</p>
	<p>
		<strong>Longitude:</strong>
		<%= @customer.longitude %>
	</p>
	<%= link_to 'Edit', edit_customer_path(@customer) %> |
	<%= link_to 'Back', customers_path %>
</div>
<br><br>
<input id="location_area" value="" hidden="true" readonly/>
<div id="map_out" style='width: 100%; height: 500px;'></div>
<br><br>
<script type="text/javascript">
	var nearestZones = [];
	var found = [];
	var bool_value = false;
	var heading = document.createElement("H3");
	var smallheading = document.createElement("H5");
	var currentDistance;
	var headingText = document.createTextNode("This Delivery Address is within Delivery Zone of following restaurants.");
	latLngA = new google.maps.LatLng(<%= @customer.latitude %>, <%= @customer.longitude %>);
	<% if @Restaurant.present? %>
		<%for rest in @Restaurant %>
			latLngB = new google.maps.LatLng (<%=rest.latitude%>, <%=rest.longitude%>);
			currentDistance = google.maps.geometry.spherical.computeDistanceBetween (latLngA, latLngB);
			if((currentDistance/1000) < 10){
				var x = <%= raw rest.area %>;
				var arr = $.map(x, function(el) { return el });
				var shapeType = arr[0].type;
				if(shapeType=="CIRCLE"){
					var circle_radius = arr[0].radius;
					var point = {lat: arr[0].geometry[0], lng: arr[0].geometry[1]};
					latLngAA = new google.maps.LatLng (point);
					if(google.maps.geometry.spherical.computeDistanceBetween (latLngA, latLngAA) < circle_radius){
						bool_value = true;
						bool_value_loc = bool_value;
					}
					}else if (shapeType=="POLYGON"){
						var latlngarray = []; arr[0].geometry.forEach(function(item){
						item.forEach(function(latlong){
							latlngarray.push({lat: latlong[0], lng: latlong[1]});
							var triangleShape = new google.maps.Polygon({paths: [latlngarray]});
							bool_value = (google.maps.geometry.poly.containsLocation(latLngA, triangleShape));
						});
					});
				}else if(shapeType=="RECTANGLE"){
					var rectangleCorners = [];
					arr[0].geometry.forEach(function(item){
						rectangleCorners.push(item[0]);
						rectangleCorners.push(item[1]);
					});
					var rectangleShape = new google.maps.Rectangle({
						bounds: new google.maps.LatLngBounds(
							new google.maps.LatLng(rectangleCorners[0], rectangleCorners[1]),
							new google.maps.LatLng(rectangleCorners[2], rectangleCorners[3])
							),
					});
					bool_value = rectangleShape.getBounds().contains(latLngA);
					}else if(shapeType=="POLYLINE"){
						bool_value = false;
					}else{
						bool_value = false;
					}
					if(bool_value==true){
						found.push(x);
    					heading.appendChild(headingText)
    					var t = document.createTextNode("<%= raw rest.title %> Restaurant is "+ (currentDistance/1000).toFixed(2) +" Kilometers away and Delivery Cost is <%= raw rest.inside_zone %> Dollars.");
    						smallheading.appendChild(t);
    						document.body.appendChild(heading);
    						document.body.appendChild(smallheading);
    						smallheading.appendChild(document.createElement("br"));
					}
					 else{
						nearestZones.push({restaurant_object: <%= raw rest.to_json %>, dist: currentDistance});
					}
				}
		<%end%>
	<%end%>
	if(found[length]==null){
		if(nearestZones[length] != null){
			headingText = document.createTextNode("This Address is not in any Restuarant's Delivery Zone, but Following Restaurants are within the 10KM of the Delivery Address.");
			heading.appendChild(headingText);
			document.body.appendChild(heading);
			nearestZones.forEach(function(index){
				var t = document.createTextNode(index.restaurant_object.title +  " Restaurant is "+ (index.dist/1000).toFixed(2) +"  Kilometers away and Delivery Cost is " + index.restaurant_object.outsite_zone + " Dollars. ");
    			smallheading.appendChild(t);
    			document.body.appendChild(smallheading);
				smallheading.appendChild(document.createElement("br"));
			});
		}else{
			headingText = document.createTextNode("This Address is not in Either any Restuarant's Delivery Zone nor in 10KM range of the Delivery Address.");
			heading.appendChild(headingText);
			document.body.appendChild(heading);
		}

	}
	function loadfoundLocation(){
	var goo = google.maps,
	map_out = new goo.Map(document.getElementById('map_out'),
	{ zoom: 12, center: new goo.LatLng(<%= @customer.latitude %>, <%= @customer.longitude%>)}),
	byId = function(s){return document.getElementById(s)};
	new goo.Marker({
		position: {lat: <%= @customer.latitude %>, lng: <%= @customer.longitude%> },
		map: map_out,
		title: "Delivery Order Address!",
	});
	found.forEach(function(locationss){
		locationss.forEach(function(loca){
			document.getElementById('location_area').value = JSON.stringify([loca]);
			IO.OUT(JSON.parse(byId('location_area').value),map_out);
		});
	});
	}
	$(document).ready( loadfoundLocation );
	$(document).on("page:load", loadfoundLocation );
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Find Restaurants", root_path, class:'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Restaurants", locations_path%></li>
      <li><%= link_to "Orders", customers_path%></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>FindLoc</title>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="//maps.google.com/maps/api/js?key=AIzaSyCPKiCAwwRASagRLHYWveJmaDa0yAME6V4&libraries=drawing,geometry"></script>
      <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing,geometry"></script> -->
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    	<%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :location_title, :required=> true %>
  </div>
  <br>
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :location_address, :required=> true %>
  </div>
  <br>
  <div class="field">
    Delivery Charges <%= form.label :inside_zone %> of Restaurant:
    <%= form.text_field :inside_zone, id: :location_inside, :required=> true %>
  </div>
  <div class="field">
    Delivery Charges <%= form.label :outsite_zone %> of Restaurant:
    <%= form.text_field :outsite_zone, id: :location_outside, :required=> true %>
  </div>
  <div class="field">
    <%= form.text_field :area, id: :location_area, :hidden => true %>
  </div>
  <div class="actions">
    <%= form.submit :class=> "btn btn-success", id: :clickFrom%>
  </div>
<% end %>

app/views/locations/edit.html.erb
<span class="text-center">
	<h1>Editing Resturant</h1>

	<%= render 'form', location: @location %>
	<div class="text-center">
	<%= link_to 'Show', @location%> |
	<%= link_to 'Back', locations_path %>
	</div>
</span>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <input id="location_area" value="" hidden="true" />
  <div class="text-center">
    <h1>Our Restaurants</h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Address</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @locations.each do |location| %>
          <tr>
            <td><%= location.title %></td>
            <td><%= location.address %></td>
            <td><%= location.latitude %></td>
            <td><%= location.longitude %></td>
            <td><%= link_to 'Show', location %></td>
            <td><%= link_to 'Edit', edit_location_path(location) %></td>
            <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <%= link_to 'Register New Restaurant', new_location_path %>
    <br>
    <br>
    <div id="map_out" style='width: 100%; height: 500px;'>
    </div>
    <br>
  </div>
</div>
<script type="text/javascript">
    var locations_all = [];
    <% @locations.each do |rest|%>
        var x = <%= raw rest.area %>;
        locations_all.push(x);
    <%end%> 
    function loadlocations_allLocation(){
        var goo = google.maps,
        map_out = new goo.Map(document.getElementById('map_out'), 
                    { zoom: 10, center: new goo.LatLng(40.7128, -74.0060)}),
        byId = function(s){return document.getElementById(s)};
        <% @locations.each do |rest| %>
          var markers = new goo.Marker({
            position: {lat: <%= rest.latitude %>, lng: <%= rest.longitude%> },
            map: map_out,
            title: '<%= rest.title %>',
          });
        <% end %>
        locations_all.forEach(function(locationss){
          locationss.forEach(function(loca){
            document.getElementById('location_area').value = JSON.stringify([loca]);
            IO.OUT(JSON.parse(byId('location_area').value),map_out);
          });
        }); 
      }
      $(document).ready( loadlocations_allLocation );
      $(document).on("page:load", loadlocations_allLocation );
</script>

app/views/locations/new.html.erb
<div class="container">
	<div class="text-center">
		<h1>Please Enter Restaurant Address</h1>

		<%= render 'form', location: @location %>
		<div class="container text-center">
			<h3>Define Delivery Zone around your Restaurant.</h3>
			<div class="map" id="map_in" style='width: 100%; height: 600px;'>

			</div>
			<div style="text-align:center">
				<input id="clear_shapes" value="Clear Zone" type="button"/>
				<input id="save_encoded" value="Save Encoded" type="button" hidden="true" />
				<input id="restore" value="Restore Zone" type="button" hidden="true" />
			</div>
			<div id="map_out" style='width: 100%; height: 400px;' hidden="true">
			</div>
		</div>
		<%= link_to 'Back', locations_path %>
	</div>
</div>
<script type="text/javascript">
  $(document).ready( initialize );
  $(document).on("page:load", initialize );
</script>

app/views/locations/show.html.erb
<h2 class="text-center"> Restaurant Details</h2>
<p id="notice"><%= notice %></p>
<p class="text-center">
	<strong>Restaurant Address:</strong>
	<%= @location.address %>
</p>
<p class="text-center">
	<strong>Delivery Charges Inside Restaurant Zone:</strong>
	<%= @location.inside_zone %>
</p>
<p class="text-center">
	<strong>Delivery Charges Outside Restaurant Zone:</strong>
	<%= @location.outsite_zone %>
</p>
<input id="location_area" value="<%= @location.area%>" hidden="true" style="width:100%" readonly/>
<input id="restore" value="Restore Zone" type="button" hidden="true"/>
<div id="map_out" style='width: 100%; height: 500px;'></div>
<%= link_to 'Edit ', edit_location_path(@location) %> |
<%= link_to ' Back', locations_path %>
<br>
<script type="text/javascript">
	var data = document.getElementById("location_area").value;
	var arr = $.map($.parseJSON(data), function(el) { return el });
	function load_location()
	{   
	    var goo = google.maps,
	    map_out = new goo.Map(document.getElementById('map_out'), 
	                { zoom: 12, center: new goo.LatLng(<%= @location.latitude %>, <%= @location.longitude %>)}),
	    shapes = [],
	    byId = function(s){return document.getElementById(s)};
	      if(this.shapes){
	        for(var i=0;i<this.shapes.length;++i){
	              this.shapes[i].setMap(null);
	        }
	      }
	      this.shapes=IO.OUT(JSON.parse(byId('location_area').value),map_out);
	    var marker = new goo.Marker({
	      position: {lat: <%= @location.latitude %>, lng: <%= @location.longitude %> },
	      map: map_out,
	      title: 'KFC!'
	      });
	}
	$(document).ready( load_location );
	$(document).on("page:load", load_location );
</script>